# Generated by Django 3.2.3 on 2021-06-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailextraorder',
            name='all_extras',
            field=models.ManyToManyField(related_name='all_extras_in_orders', to='pizza_app.Pizza'),
        ),
    ]
