# Generated by Django 3.2.3 on 2021-06-10 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0003_alter_detailextraorder_all_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='special_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizzasize',
            name='discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pizzasize',
            name='special_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SpecialDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('discount_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts_created', to='pizza_app.user')),
                ('users_have_discount', models.ManyToManyField(related_name='my_discounts', to='pizza_app.User')),
            ],
        ),
    ]
