# Generated by Django 3.2.3 on 2021-06-10 05:47

from django.db import migrations, models
import django.db.models.deletion
import pizza_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0004_auto_20210610_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, validators=[pizza_app.models.ValidarLongitudMinima])),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, validators=[pizza_app.models.ValidarLongitudMinima])),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, validators=[pizza_app.models.ValidarLongitudMinima])),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunas', to='pizza_app.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='pizza_app.region'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=45, validators=[pizza_app.models.ValidarLongitudMinima])),
                ('street', models.CharField(max_length=45, validators=[pizza_app.models.ValidarLongitudMinima])),
                ('number', models.IntegerField()),
                ('appartment', models.CharField(default=None, max_length=15)),
                ('floor', models.CharField(default=None, max_length=15)),
                ('comments', models.CharField(max_length=45, validators=[pizza_app.models.ValidarLongitudMinima])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='pizza_app.comuna')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_addresses', to='pizza_app.user')),
            ],
        ),
    ]
