# Generated by Django 3.2.3 on 2021-06-12 03:34

from django.db import migrations, models
import django.db.models.deletion
import pizza_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0005_auto_20210610_0547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='fee_delvery',
            new_name='fee_delivery',
        ),
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.CharField(default='.', max_length=45, validators=[pizza_app.models.ValidarLongitudMinima]),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='IngredientSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=45, validators=[pizza_app.models.ValidarLongitudMinima])),
                ('type_size', models.IntegerField()),
                ('price', models.IntegerField()),
                ('discount', models.BooleanField(default=False)),
                ('special_price', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='pizza_app.ingredient')),
            ],
        ),
    ]
