# Generated by Django 3.2.3 on 2021-06-12 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0006_auto_20210612_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientsize',
            name='type_size',
        ),
    ]
