# Generated by Django 3.2.3 on 2021-06-12 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0008_ingredient_opcional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='opcional',
            new_name='optional',
        ),
    ]
