# Generated by Django 3.2.3 on 2021-06-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0009_rename_opcional_ingredient_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='orden',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
