# Generated by Django 3.2.3 on 2021-06-12 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0011_ingredientsize_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='size',
        ),
        migrations.DeleteModel(
            name='PizzaSize',
        ),
    ]
