# Generated by Django 3.2.3 on 2021-06-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0012_auto_20210612_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientsize',
            name='multiple_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ingredientsize',
            name='special_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='special_price',
            field=models.IntegerField(default=0),
        ),
    ]
