# Generated by Django 3.2.3 on 2021-06-12 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0015_rename_ingredientsize_ingredientoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientoption',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='pizza_app.ingredient'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='all_ingredients',
            field=models.ManyToManyField(related_name='all_in_pizzas', to='pizza_app.IngredientOption'),
        ),
    ]
