# Generated by Django 3.2.3 on 2021-06-12 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0016_auto_20210612_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientoption',
            old_name='size',
            new_name='option',
        ),
    ]
