# Generated by Django 3.2.3 on 2021-06-13 15:05

from django.db import migrations, models
import pizza_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0017_rename_size_ingredientoption_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='image',
            field=models.CharField(default='', max_length=45, validators=[pizza_app.models.ValidarLongitudMinima]),
            preserve_default=False,
        ),
    ]
