# Generated by Django 3.2.3 on 2021-06-14 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0019_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailextraorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_extras_order', to='pizza_app.order'),
        ),
        migrations.AlterField(
            model_name='detailpizzaorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_pizzas_order', to='pizza_app.order'),
        ),
    ]
